import requests

GROQ_API_KEY = "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"
GROQ_API_ENDPOINT = "https://api.groq.com/openai/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {GROQ_API_KEY}",
    "Content-Type": "application/json"
}

prompt = """
You are an expert SQL assistant. Generate an SQL query for the following natural language request:
NL: Find the total revenue generated by campaigns that were successful, defined as campaigns with an actual spent less than the budget.
SQL:
"""

data = {
    "model": "mixtral-8x7b-32768",
    "messages": [{"role": "user", "content": prompt}],
    "temperature": 0,
    "max_tokens": 500,
}

response = requests.post(GROQ_API_ENDPOINT, headers=headers, json=data)

if response.status_code == 200:
    print("✅ Success:", response.json()['choices'][0]['message']['content'].strip())
else:
    print("❌ Error:", response.text)